# .circleci/config.yml

version: 2.1
jobs:
  build:
    docker:
      - image: reiniscirpons/hpcombi-env-arm64v8:v1
    resource_class: arm.medium
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
