name: CI
on: [pull_request, push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   test-amd64:
      name: "ubuntu-latest | g++ | amd64"
      timeout-minutes: 60
      runs-on: ubuntu-latest
      env:
         CXX: "ccache g++"
         CXXFLAGS: "-fdiagnostics-color"
         CMAKE_CXX_COMPILER: "ccache g++"
      steps:
         - name: "Checkout HPCombi repo . . ."
           uses: actions/checkout@v3
         - name: "Setup ccache . . ."
           uses: Chocobo1/setup-ccache-action@v1
           with:
             update_packager_index: false
             override_cache_key: ${{ runner.os }}-${{ github.ref }}
             override_cache_key_fallback: ${{ runner.os }}
         - name: "Install dependencies . . ."
           run: |
                sudo apt-get --yes update
                sudo apt-get install --yes ccache
                sudo apt-get install --yes libbenchmark-dev
         - name: "Build + run HPCombi tests . . ."
           run: |
              mkdir build
              cd build
              cmake -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release ..
              cd tests
              make
              ./test_all

   test-arm64:
      name: "ubuntu-latest | g++ | arm64"
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
         - name: "Run CircleCI job"
           id: "circleci_1"
           uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
           with:
             target-slug: ${{ secrets.CCI_SLUG }}
           env:
             CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
